const appUrl = process.env.APP_URL;
export default {
  title: "Subscriptions",
  path: "sales/subscriptions",
  permission: "sls_subscriptions.list",

  content: {
    type: "crud",
    value: {
      endpoint: "/table/sls_subscriptions",
      create: {
        label: "Create",
        icon: "plus",
        permission: "sls_subscriptions.create",
        title: "Create Subscription",
        modalClass: "modal-xl",
        fields: [
          {
            name: "organization_id",
            label: "Organization",
            type: "select2",
            dropdownParent: "#create-modal",
            ajax: {
              useBearer: true,
              term: "search",
              response: { id: "id", text: "name" },
              url: appUrl + "/table/organizations",
            },
          },
          {
              name: "customer_id",
              label: "Customer",
              type: "select2",
              className: 'col-md-6',
              dropdownParent: "#create-modal",
              ajax: {
                  useBearer: true,
                  term: "search",
                  response: { id: "id", text: "reference.name" },
                  url: appUrl + "/table/sls_customers",
              },
          },
          {
            name: "plan_id",
            label: "Subscription Plan",
            type: "select2",
            className: 'col-md-6',
            dropdownParent: "#create-modal",
            ajax: {
              useBearer: true,
              term: "search",
              response: { id: "id", text: "name" },
              url: appUrl + "/table/sls_subscription_plans",
            },
          },
          {
            name: "code",
            label: "Code",
            type: "text",
          },
          {
            name: "start_date",
            label: "Start Date",
            type: "datePicker",
            className: "col-md-6",
          },
          {
            name: "end_date",
            label: "End Date",
            type: "datePicker",
            className: "col-md-6",
          },
          {
            name: "next_billing_date",
            label: "Next Billing Date",
            type: "datePicker",
            className: "col-md-6",
          },
          {
            name: "next_reminder_date",
            label: "Next Reminder Date",
            type: "datePicker",
            className: "col-md-6 mb-3",
          },
          {
            name: "auto_renew",
            label: "Auto Renew",
            type: "select",
            className: "col-md-6",
            defaultValue: "1",
            options: [
              { label: "Yes", value: "1" },
              { label: "No", value: "0" },
            ],
          },
          {
            name: "status",
            label: "Status",
            type: "select",
            className: "col-md-6",
            defaultValue: "active",
            options: [
              { label: "Active", value: "active" },
              { label: "Paused", value: "paused" },
              { label: "Cancelled", value: "cancelled" },
              { label: "Expired", value: "expired" },
            ],
          },
          {
            name: "items",
            label: "Items",
            type: "tableItems",
            columns: [
              {
                columnLabel: "Product",
                name: "product_id",
                type: "select2",
                ajax: {
                  useBearer: true,
                  term: "search",
                  response: { id: "id", text: "item_name_record_type" },
                  url: appUrl + "/table/sls_products",
                },
              },
              { columnLabel: "Qty", name: "qty", type: "number" },
            ],
          },
        ],
      },
      actions: [
        {
          label: "Detail",
          type: "view",
          icon: "eye",
          permission: "sls_subscriptions.single",
          title: "Subscription Detail",
          modalClass: "modal-lg",
          fields: [
            {
              name: "organization_name",
              label: "Organization",
              type: "text",
              className: "col-md-6",
            },
            {
              name: "plan.name",
              label: "Subscription Plan",
              type: "text",
              className: "col-md-6",
            },
            {
              name: "reference.name",
              label: "Customer",
              type: "text",
              className: "col-md-6",
            },
            {
              name: "plan.price_format",
              label: "Subscription Price",
              type: "text",
              className: "col-md-6",
            },
            {
              name: "start_date",
              label: "Start Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "end_date",
              label: "End Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "next_billing_date",
              label: "Next Billing Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "next_reminder_date",
              label: "Next Reminder Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "auto_renew",
              label: "Auto Renew",
              type: "switch",
              className: "col-md-6",
            },

            {
              name: "status",
              label: "Status",
              type: "status-badge",
              className: "col-md-6",
              badge: {
                color: {
                  active: "success",
                  paused: "warning",
                  cancelled: "secondary",
                  expired: "danger",
                },
                label: {
                  active: "Active",
                  paused: "Paused",
                  cancelled: "Cancelled",
                  expired: "Expired",
                },
              },
            },
            {
              name: "items",
              label: "Items",
              type: "tableItems",
              columns: [
                {
                  columnLabel: "Product",
                  name: "product.item.name",
                  type: "text",
                  className: "text-start",
                },
                {
                  columnLabel: "Qty",
                  name: "qty",
                  type: "number",
                  className: "text-end",
                },
              ],
            },
          ],
        },
        {
          label: "Edit",
          type: "edit",
          icon: "edit-2",
          permission: "sls_subscriptions.update",
          title: "Edit Sales Subscription",
          // show_if: { field: "status", operator: "equals", value: "pending" },
          modalClass: "modal-md",
          fields: [
            {
              name: "organization_id",
              label: "Organization",
              type: "select2",
              dropdownParent: "#edit-modal",
              ajax: {
                useBearer: true,
                term: "search",
                response: { id: "id", text: "label" },
                initList: {
                  url: "/table/organizations",
                  key: "organization_id",
                  response: { id: "id", text: "name" },
                },
                url: appUrl + "/table/organizations",
                urlParams: [{ key: "id", value: "id" }],
              },
            },
            {
              name: "customer_id",
              fieldValue: 'customer.id',
              label: "Customer",
              type: "select2",
              className: 'col-md-6',
              dropdownParent: "#edit-modal",
              ajax: {
                useBearer: true,
                term: "search",
                response: { id: "id", text: "reference.name" },
                initList: {
                  url: "/app/sales/get-customer-by-subs-id",
                  key: "id",
                  response: { id: "id", text: "reference.name" },
                },
                url: appUrl + "/table/sls_customers",
                urlParams: [{ key: "id", value: "id" }],
              },
            },
            {
              name: "plan_id",
              label: "Subscription Plan",
              type: "select2",
              className: 'col-md-6',
              dropdownParent: "#edit-modal",
              ajax: {
                useBearer: true,
                term: "search",
                response: { id: "id", text: "name" },
                initList: {
                  url: "/table/sls_subscription_plans",
                  key: "plan_id",
                  response: { id: "id", text: "name" },
                },
                url: appUrl + "/table/sls_subscription_plans",
                urlParams: [{ key: "id", value: "id" }],
              },
            },
            {
              name: "code",
              label: "Code",
              type: "text",
            },
            {
              name: "start_date",
              label: "Start Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "end_date",
              label: "End Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "next_billing_date",
              label: "Next Billing Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "next_reminder_date",
              label: "Next Reminder Date",
              type: "datePicker",
              className: "col-md-6",
            },
            {
              name: "auto_renew",
              label: "Auto Renew",
              type: "switch",
              className: "col-md-6",
            },
            {
              name: "status",
              label: "Status",
              type: "select",
              className: "col-md-6",
              defaultValue: "active",
              options: [
                { label: "Active", value: "active" },
                { label: "Paused", value: "paused" },
                { label: "Cancelled", value: "cancelled" },
                { label: "Expired", value: "expired" },
              ],
            },
            
          ],
        },
        {
          label: "Delete",
          type: "delete",
          icon: "trash",
          class: "text-danger",
          permission: "sls_subscriptions.delete",
          show_if: { field: "status", operator: "equals", value: "active" },
        },
      ],

      columns: [
        {
          key: "organization_name",
          label: "Organization",
          sortable: true,
          searchable: true,
        },
        {
          key: "code",
          label: "Code",
          searchable: true,
        },
        {
          key: "reference.name",
          label: "Customer",
          searchable: true,
        },
        {
          key: "plan.name",
          label: "Subscription Plan",
          sortable: true,
          searchable: true,
        },
        {
          key: "plan.price_format",
          label: "Subscription Price",
          sortable: true,
          searchable: true,
        },
        {
          key: "start_date",
          label: "Start Date",
          sortable: true,
          searchable: true,
        },
        {
          key: "end_date",
          label: "End Date",
          sortable: true,
          searchable: true,
        },
        {
          key: "next_billing_date",
          label: "Next Billing Date",
          sortable: true,
          searchable: true,
        },
        {
          key: "next_reminder_date",
          label: "Next Reminder Date",
          sortable: true,
          searchable: true,
        },
        {
          key: "auto_renew",
          label: "Auto Renew",
          sortable: true,
          searchable: true,
        },
        {
          key: "status",
          label: "Status",
          sortable: true,
          searchable: true,
          type: "status-badge",
          badge: {
            color: {
              active: "success",
              paused: "secondary",
              cancelled: "warning",
              expired: "danger",
            },
            label: {
              active: "Active",
              paused: "Paused",
              cancelled: "Cancelled",
              expired: "Expired",
            },
          },
        },
        {
          key: "created_at",
          label: "Created At",
          sortable: true,
          type: "date",
        },
        {
          key: "updated_at",
          label: "Updated At",
          sortable: true,
          type: "date",
        },
      ],
    },
  },
};
